/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_chainfire_opendelta_Native */

#ifndef _Included_eu_chainfire_opendelta_Native
#define _Included_eu_chainfire_opendelta_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_chainfire_opendelta_Native
 * Method:    zipadjust
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_eu_chainfire_opendelta_Native_zipadjust
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     eu_chainfire_opendelta_Native
 * Method:    dedelta
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_eu_chainfire_opendelta_Native_dedelta
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
